import { FormInputState } from "./input.state";
import { FormInputDirectionEnum, FormInputSizeEnum, FormInputStatusEnum, FormInputTypeEnum } from '@data-access-form';

export const formInputInitialState: FormInputState = {
  id: '',
  canResize: false,
  canShowError: false,
  canShowErrorMessage: false,
  canShowSuccess: false,
  canShowSuccessMessage: false,
  canShowWarning: false,
  canShowWarningMessage: false,
  inputExisted: false,
  successMessage: '',
  errorMessage: '',
  warningMessage: '',
  timeSleep: 0,
  required: false,
  nodeName: 'input',
  placeholder: '',
  maxlength: 0,
  existWhite: false,
  minlength: 0,
  className: '',
  label: '',
  size: FormInputSizeEnum.M,
  status: FormInputStatusEnum.Neutral,
  length: 0,
  focused: false,
  valid: false,
  hardValid: true,
  touched: false,
  dirty: false,
  disabled: false,
  readonly: false,
  inputType: FormInputTypeEnum.Text,
  direction: FormInputDirectionEnum.Column,
  value: undefined,
  customClass: '',
  name: '',
  wrapperClass: 'wrapper-form-input',
  wrapperLocale: 'LIBS.SHARED.UI.FORM.INPUT'
};
