export enum CommonIconAlertEnum {
  AddAlert = 'add_alert',
  Announcement = 'announcement',
  Block = 'block',
  Campaign = 'campaign',
  Cancel = 'cancel',
  CircleNotifications = 'circle_notifications',
  ContactSupport = 'contact_support',
  Dangerous = 'dangerous',
  DeleteForever = 'delete_forever',
  DisabledByDefault = 'disabled_by_default',
  DisabledVisible = 'disabled_visible',
  Error = 'error',
  ErrorOutline = 'error_outline',
  Flag = 'flag',
  FlagOutline = 'flag_outline',
  Help = 'help',
  HelpOutline = 'help_outline',
  HelpSquare = 'help_square',
  Info = 'info',
  InfoOutline = 'info_outline',
  InfoItalic = 'info_italic',
  InfoItalicSolid = 'info_italic_solid',
  InfoItalicOutline = 'info_italic_outline',
  NotificationAdd = 'notification_add',
  NotificationImportant = 'notification_important',
  Notifications = 'notifications',
  NotificationsActive = 'notifications_active',
  NotificationsOff = 'notifications_off',
  NotificationsOutline = 'notifications_outline',
  NotificationsPaused = 'notifications_paused',
  Report = 'report',
  ReportOff = 'report_off',
  ReportOutline = 'report_outline',
  Reviews = 'reviews',
  Warning = 'warning',
  WarningOutline = 'warning_outline',
}

export enum CommonIconArrowEnum {
  ArrowBack = 'arrow_back',
  ArrowBackIos = 'arrow_back_ios',
  ArrowCircleDown = 'arrow_circle_down',
  ArrowCircleUp = 'arrow_circle_up',
  ArrowDownward = 'arrow_downward',
  ArrowDropDown = 'arrow_drop_down',
  ArrowDropUp = 'arrow_drop_up',
  ArrowForward = 'arrow_forward',
  ArrowForwardIos = 'arrow_forward_ios',
  ArrowLeft = 'arrow_left',
  ArrowRight = 'arrow_right',
  ArrowRightAlt = 'arrow_right_alt',
  ArrowUpward = 'arrow_upward',
  ChevronLeft = 'chevron_left',
  ChevronRight = 'chevron_right',
  CompareArrows = 'compare_arrows',
  East = 'east',
  ExpandLess = 'expand_less',
  ExpandMore = 'expand_more',
  FirstPage = 'first_page',
  Forward = 'forward',
  Fullscreen = 'fullscreen',
  FullscreenExit = 'fullscreen_exit',
  ImportExport = 'import_export',
  LastPage = 'last_page',
  North = 'north',
  NorthEast = 'north_east',
  NorthWest = 'north_west',
  South = 'south',
  SouthEast = 'south_east',
  SouthWest = 'south_west',
  SubdirectoryArrowLeft = 'subdirectory_arrow_left',
  SubdirectoryArrowRight = 'subdirectory_arrow_right',
  SwitchLeft = 'switch_left',
  SwitchRight = 'switch_right',
  UnfoldLess = 'unfold_less',
  UnfoldMore = 'unfold_more',
  West = 'west',
}

export enum CommonIconBasicEnum {
  CheckOutline = 'check-outline',
  CheckSolid = 'check-solid',
}

export enum CommonIconCheckEnum {
  Check = 'check',
  CheckCircle = 'check_circle',
  CheckCircleOutline = 'check_circle_outline',
  CheckDoneAll = 'check_done_all',
  CheckDoneOutline = 'check_done_outline',
  Checklist = 'checklist',
}

export enum CommonIconConnectEnum {
  ThreeP = '3p',
  AddIcCall = 'add_ic_call',
  AddLink = 'add_link',
  AlternateEmail = 'alternate_email',
  AttachEmail = 'attach_email',
  Bluetooth = 'bluetooth',
  BluetoothConnected = 'bluetooth_connected',
  BluetoothDisabled = 'bluetooth_disabled',
  BluetoothSearching = 'bluetooth_searching',
  Call = 'call',
  CallEnd = 'call_end',
  CallMade = 'call_made',
  CallMissed = 'call_missed',
  Chat = 'chat',
  ChatBubble = 'chat_bubble',
  ChatBubbleOutline = 'chat_bubble_outline',
  ContactMail = 'contact_mail',
  ContactPhone = 'contact_phone',
  Contacts = 'contacts',
  Drafts = 'drafts',
  Email = 'email',
  EmailOutline = 'email_outline',
  ImportContacts = 'import_contacts',
  Inbox = 'inbox',
  Link = 'link',
  LinkOff = 'link_off',
  LiveHelp = 'live_help',
  LocationOff = 'location_off',
  LocationOn = 'location_on',
  MailOutline = 'mail_outline',
  MarkEmailRead = 'mark_email_read',
  MarkEmailUnread = 'mark_email_unread',
  Message = 'message',
  Nfc = 'nfc',
  PhoneDisabled = 'phone_disabled',
}

export enum CommonIconCryptoEnum {
  OneInch = '1inch',
  SpaceDot = '_dot',
  SpaceEos = '_eos',
  SpaceUsdc = '_usdc',
  SpaceUsdt = '_usdt',
  Aave = 'aave',
  Ada = 'ada',
  Algo = 'algo',
  Ankr = 'ankr',
  Ardr = 'ardr',
  Atom = 'atom',
  Audt = 'audt',
  Ava = 'ava',
  Bake = 'bake',
  Band = 'band',
  Bat = 'bat',
  Bch = 'bch',
  Bnb = 'bnb',
  Brl = 'brl',
  Btc = 'btc',
  Btt = 'btt',
  Busd = 'busd',
  Cake = 'cake',
  Chr = 'chr',
  Chz = 'chz',
  Comp = 'comp',
  Dai = 'dai',
  Dash = 'dash',
  Doge = 'doge',
  Egld = 'egld',
  Enj = 'enj',
  Etc = 'etc',
  Eth = 'eth',
  Eur = 'eur',
  Fil = 'fil',
  Fio = 'fio',
  Ftm = 'ftm',
  Gbp = 'gbp',
  Grt = 'grt',
  Iota = 'iota',
  Ksm = 'ksm',
  Link = 'link',
  Ltc = 'ltc',
  Luna = 'luna',
  Mana = 'mana',
  Matic = 'matic',
  Mkr = 'mkr',
  Neo = 'neo',
  Rune = 'rune',
  Shib = 'shib',
  Snx = 'snx',
  Sol = 'sol',
  Sxp = 'sxp',
  Theta = 'theta',
  Trx = 'trx',
  Uni = 'uni',
  Vet = 'vet',
  Waves = 'waves',
  Win = 'win',
  Wrx = 'wrx',
  Xem = 'xem',
  Xlm = 'xlm',
  Xrp = 'xrp',
  Xtz = 'xtz',
  Yfi = 'yfi',
  Zec = 'zec',
  Zil = 'zil',
}

export enum CommonIconCursorEnum {
  Alias = 'alias',
  Cell = 'cell',
  ColResize = 'col-resize',
  ContextMenu = 'context-menu',
  Copy = 'copy',
  CrossHair = 'cross-hair',
  Default = 'default',
  DownResize = 'down-resize',
  EResize = 'e-resize',
  EwResize = 'ew-resize',
  Grab = 'grab',
  Grabbing = 'grabbing',
  Help = 'help',
  LeftResize = 'left-resize',
  Move = 'move',
  NResize = 'n-resize',
  NeResize = 'ne-resize',
  NoDrop = 'no-drop',
  NotAllowed = 'not-allowed',
  NsResize = 'ns-resize',
  NwResize = 'nw-resize',
  NwseResize = 'nwse-resize',
  Pointer = 'pointer',
  Poof = 'poof',
  Progress = 'progress',
  RightResize = 'right-resize',
  RowResize = 'row-resize',
  SResize = 's-resize',
  ScreenshotWindow = 'screenshot-window',
  SeResize = 'se-resize',
  SwResize = 'sw-resize',
  Text = 'text',
  UpResize = 'up-resize',
  WResize = 'w-resize',
  Wait = 'wait',
  ZoomIn = 'zoom-in',
  ZoomOut = 'zoom-out',
}

export enum CommonIconDataEnum {
  Analytics = 'analytics',
  DonutLarge = 'donut_large',
  DonutSmall = 'donut_small',
  Insights = 'insights',
  StackedBarChart = 'stacked_bar_chart',
}

export enum CommonIconDeviceEnum {
  Android = 'android',
  Api = 'api',
  AppBlocking = 'app_blocking',
  AppSettingsAlt = 'app_settings_alt',
  BugReport = 'bug_report',
  Build = 'build',
  BuildCircle = 'build_circle',
  Desktop = 'desktop',
  Laptop = 'laptop',
  MobileFriendly = 'mobile_friendly',
  MobileOff = 'mobile_off',
  Mouse = 'mouse',
  NoSim = 'no_sim',
  OfflineShare = 'offline_share',
  PhoneAndroid = 'phone_android',
  PhoneIphone = 'phone_iphone',
  Phonelink = 'phonelink',
  PhonelinkErase = 'phonelink_erase',
  PhonelinkLock = 'phonelink_lock',
  PhonelinkOff = 'phonelink_off',
  PhonelinkRing = 'phonelink_ring',
  PhonelinkSetup = 'phonelink_setup',
  SecurityUpdate = 'security_update',
  SecurityUpdateGood = 'security_update_good',
  SecurityUpdateWarning = 'security_update_warning',
  SettingsSuggest = 'settings_suggest',
  Usb = 'usb',
  UsbOff = 'usb_off',
}

export enum CommonIconFileEnum {
  Assessment = 'assessment',
  Assignment = 'assignment',
  AssignmentInd = 'assignment_ind',
  AssignmentLate = 'assignment_late',
  AssignmentReturn = 'assignment_return',
  AssignmentReturned = 'assignment_returned',
  AssignmentTurnedIn = 'assignment_turned_in',
  AttachFile = 'attach_file',
  Attachment = 'attachment',
  Book = 'book',
  BookOnline = 'book_online',
  BookOutline = 'book_outline',
  Bookmark = 'bookmark',
  Cloud = 'cloud',
  CloudCircle = 'cloud_circle',
  CloudDone = 'cloud_done',
  CloudDownload = 'cloud_download',
  CloudOff = 'cloud_off',
  CloudUpload = 'cloud_upload',
  ContactPage = 'contact_page',
  ContactPageOne = 'contact_page-1',
  Description = 'description',
  Download = 'download',
  DownloadDone = 'download_done',
  DownloadForOffline = 'download_for_offline',
  Downloading = 'downloading',
  Inventory = 'inventory',
  ListAlt = 'list_alt',
  Task = 'task',
}

export enum CommonIconFinanceEnum {
  AccountBalance = 'account_balance',
  AccountBalanceOutline = 'account_balance_outline',
  AccountBalanceWallet = 'account_balance_wallet',
  AttachMoney = 'attach_money',
  CreditCard = 'credit_card',
  CreditCardOff = 'credit_card_off',
  CreditScore = 'credit_score',
  MonetizationOn = 'monetization_on',
  MoneyOff = 'money_off',
  Payments = 'payments',
  PriceChange = 'price_change',
  PriceCheck = 'price_check',
  Sell = 'sell',
}

export enum CommonIconFlagEnum {
  Vietnam = 'vietnam',
  Us = 'us',
  English = 'english',
  Singapore = 'singapore',
}

export enum CommonIconGlobalEnum {
  Add = 'add',
  AddBox = 'add_box',
  AddCircle = 'add_circle',
  AddCircleOutline = 'add_circle_outline',
  AddComment = 'add_comment',
  AdsClick = 'ads_click',
  Archive = 'archive',
  Article = 'article',
  AspectRatio = 'aspect_ratio',
  AutoDelete = 'auto_delete',
  AutoRenew = 'auto_renew',
  Backspace = 'backspace',
  BrowserNotSupported = 'browser_not_supported',
  Cancel = 'cancel',
  Calculate = 'calculate',
  CameraSwitch = 'camera_switch',
  ChangeCircle = 'change_circle',
  CheckSmallOutline = 'check_small_outline',
  CheckBold = 'check_bold',
  Close = 'close',
  Contactless = 'contactless',
  ContentCopy = 'content_copy',
  ContentPaste = 'content_paste',
  ContentPasteOff = 'content_paste_off',
  CopyAll = 'copy_all',
  CopyRight = 'copy_right',
  Create = 'create',
  DarkMode = 'dark_mode',
  Delete = 'delete',
  DeleteOutline = 'delete_outline',
  DeleteSweep = 'delete_sweep',
  DragIndicator = 'drag_indicator',
  EditNote = 'edit_note',
  EditOff = 'edit_off',
  Eject = 'eject',
  ExitToApp = 'exit_to_app',
  Expand = 'expand',
  Filter = 'filter',
  FilterSort = 'filter_sort',
  FileCopy = 'file_copy',
  FilterAlt = 'filter_alt',
  FilterList = 'filter_list',
  HeadsetMic = 'headset_mic',
  Language = 'language',
  Loading = 'loading',
  Logout = 'logout',
  MinusSmallOutline = 'minus_small_outline',
  QrCode = 'qr_code',
  QrCodeScanner = 'qr_code_scanner',
  ReFresh = 'refresh',
  Remove = 'remove',
  RemoveBold = 'remove_bold',
  Resize = 'resize',
  RemoveCircle = 'remove_circle',
  RemoveCircleOutline = 'remove_circle_outline',
  Save = 'save',
  Search = 'search',
  SearchOff = 'search_off',
  SearchPageOutline = 'search_page_outline',
  Send = 'send',
  Skeleton = 'skeleton',
  SortUp = 'sort_up',
  SortDown = 'sort_down',
  Sort = 'sort',
  Settings = 'settings',
  Star = 'star',
  StarBorder = 'star_border',
  StarHalf = 'star_half',
  Wallpaper = 'wallpaper',
  ZoomIn = 'zoom_in',
  ZoomOut = 'zoom_out',
  EllipseBlue = 'ellipse_blue',
  EllipseGray = 'ellipse_gray',
}

export enum CommonIconLoadingEnum {
  SpinnerGap = 'spinner_gap',
}

export enum CommonIconLogoEnum {
  Dark = 'dark',
  Light = 'light',
}

export enum CommonIconMediaEnum {
  AddAPhoto = 'add_a_photo',
  AddToPhotos = 'add_to_photos',
  Camera = 'camera',
  Image = 'image',
  ImageNotSupported = 'image_not_supported',
  ImageSearch = 'image_search',
}

export enum CommonIconNavigationEnum {
  Apps = 'apps',
  ArrowDropDownCircle = 'arrow_drop_down_circle',
  AssistantDirection = 'assistant_direction',
  AssistantNavigation = 'assistant_navigation',
  Dashboard = 'dashboard',
  DashboardCustomize = 'dashboard_customize',
  DataExploration = 'data_exploration',
  DoubleArrow = 'double_arrow',
  Explore = 'explore',
  ExploreOff = 'explore_off',
  Menu = 'menu',
  MenuOpen = 'menu_open',
  MoreHoriz = 'more_horiz',
  MoreVert = 'more_vert',
}

export enum CommonIconPersonEnum {
  AccountBox = 'account_box',
  AccountCircle = 'account_circle',
  AccountCircleOutline = 'account_circle_outline',
  AccountTree = 'account_tree',
  HowToReg = 'how_to_reg',
  ManageAccounts = 'manage_accounts',
  PersonSearch = 'person_search',
  PermIdentity = 'perm_identity',
  PermIdentityOutline = 'perm_identity_outline',
  PeopleOutline = 'people_outline',
  Visibility = 'visibility',
  VisibilityOutline = 'visibility_outline',
  VisibilityOff = 'visibility_off',
  VisibilityOffOutline = 'visibility_off_outline',
}

export enum CommonIconSecurityEnum {
  AdminPanelSettings = 'admin_panel_settings',
  NoEncryption = 'no_encryption',
  Policy = 'policy',
  Security = 'security',
  Shield = 'shield',
  ShieldCheck = 'shield_check',
  ShieldMaybe = 'shield_maybe',
  KeyOutline = 'key-outline',
  KeySolid = 'key-solid',
  LockOutline = 'lock-outline',
  LockSolid = 'lock-solid',
}

export enum CommonIconTimeEnum {
  AccessTime = 'access_time',
  AccessTimeFilled = 'access_time_filled',
  Alarm = 'alarm',
  AlarmAdd = 'alarm_add',
  AlarmOff = 'alarm_off',
  AlarmOn = 'alarm_on',
  CalendarDateRange = 'calendar_date_range',
  CalendarEdit = 'calendar_edit',
  CalendarEvent = 'calendar_event',
  CalendarToday = 'calendar_today',
  CalendarViewDay = 'calendar_view_day',
  CalendarViewMonth = 'calendar_view_month',
  CalendarViewWeek = 'calendar_view_week',
  HourglassBottom = 'hourglass_bottom',
  HourglassTop = 'hourglass_top',
  MoreTime = 'more_time',
}

export enum CommonIconSizeEnum {
  XS = 'xs',
  S = 's',
  M = 'm',
  L = 'l',
  XL = 'xl',
  CUSTOM = 'custom'
}

export enum CommonIconPackageEnum {
  Crypto = 'crypto',
  Flag = 'flag',
  Cursor = 'cursor',
  Basic = 'basic',
  Alert = 'alert',
  Navigation = 'navigation',
  Arrow = 'arrow',
  Check = 'check',
  Connect = 'connect',
  Data = 'data',
  Device = 'device',
  File = 'file',
  Finance = 'finance',
  Media = 'media',
  Person = 'person',
  Security = 'security',
  Time = 'time',
  Loading = 'loading',
  Logo = 'logo',
  Global = 'global',
}
